server:
  port: 3003

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true

logging:
  pattern:
    level: "%5p trace=%X{traceId} span=%X{spanId} corr=%X{corr} plate=%X{plate}"
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger
