DROP TABLE IF EXISTS parking_session;
DROP TABLE IF EXISTS spot;
DROP TABLE IF EXISTS garage_sector;
DROP TABLE IF EXISTS garage;

CREATE TABLE garage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(255),
  base_price NUMERIC(15,2) NOT NULL,
  max_capacity INT NOT NULL,
  occupied INT NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE garage_sector (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  garage_id BIGINT NOT NULL,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(120) NOT NULL,
  max_capacity INT NOT NULL,
  occupied INT NOT NULL,
  is_closed BOOLEAN NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT fk_sector_garage FOREIGN KEY (garage_id) REFERENCES garage(id),
  CONSTRAINT uk_sector_garage_code UNIQUE (garage_id, code)
);

CREATE TABLE spot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  garage_id BIGINT NOT NULL,
  sector_id BIGINT NOT NULL,
  lat DOUBLE,
  lng DOUBLE,
  occupied BOOLEAN NOT NULL,
  CONSTRAINT fk_spot_garage FOREIGN KEY (garage_id) REFERENCES garage(id),
  CONSTRAINT fk_spot_sector FOREIGN KEY (sector_id) REFERENCES garage_sector(id)
);

CREATE TABLE parking_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plate VARCHAR(12) NOT NULL,
  garage_id BIGINT NOT NULL,
  sector_id BIGINT,
  spot_id BIGINT,
  status VARCHAR(10) NOT NULL,
  entry_time TIMESTAMP,
  parked_time TIMESTAMP,
  exit_time TIMESTAMP,
  effective_hourly_price NUMERIC(15,2),
  total_amount NUMERIC(15,2),
  CONSTRAINT fk_ps_garage FOREIGN KEY (garage_id) REFERENCES garage(id),
  CONSTRAINT fk_ps_sector FOREIGN KEY (sector_id) REFERENCES garage_sector(id),
  CONSTRAINT fk_ps_spot FOREIGN KEY (spot_id) REFERENCES spot(id)
);
